DROP TABLE sandbox.kb_taxonomies_log;

SQL_BREAK;

DROP TABLE sandbox.kb_taxonomies_UV;

SQL_BREAK;

DROP TABLE sandbox.kb_taxonomies_ET;

SQL_BREAK;

DROP TABLE sandbox.kb_taxonomies;

SQL_BREAK;

CREATE MULTISET TABLE sandbox.kb_taxonomies ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      locale VARCHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC,
      category_name VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      description VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      guid VARCHAR(36) CHARACTER SET UNICODE CASESPECIFIC,
      taxonomy_guid VARCHAR(36) CHARACTER SET UNICODE CASESPECIFIC,
      child_count INTEGER,
      parent VARCHAR(36) CHARACTER SET UNICODE NOT CASESPECIFIC,
      depth INTEGER,
      friendly_namePlural VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      permalink VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      seo_name VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      friendly_name_short VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      friendly_name VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      friendly_name_singular VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      friendly_name_title VARCHAR(128) CHARACTER SET UNICODE NOT CASESPECIFIC,
      relationships_size INTEGER)
PRIMARY INDEX ( locale ,category_name ,guid ,friendly_name_short );





