#!/bin/bash

usage() {
    cat <<EOF
Usage: generate_potential_kewywords host user password 

EOF
}

if [ $# -lt 3 ] ; then
    usage >&2 && exit 1
fi

DB_HOST=$1
DB_USER=$2
DB_PASSWORD=$3
if [ $# -gt 3 ] ; then
    usage >&2 && exit 1
fi

cat <<EOF

.LOGON ${DB_HOST}/${DB_USER}, ${DB_PASSWORD};
.SET WIDTH 2048
.SET MAXERROR 1

-- Create set of potential keywords and potential landing pages.
-- The same keyword may map to more than one potential landing page. 
-- Only add new keyword + URL combinations

-- Start by creating a table that contains NA cities
DELETE FROM sandbox.as_seo_cities;

INSERT INTO sandbox.as_seo_cities
SELECT location_id, 
	location_url,
	name, 
	OREPLACE(nameMedShort, ',', ''),
	ROW_NUMBER() OVER (ORDER BY population DESC) AS population_rank,
	NULL AS population_bucket,
	0 AS is_in_bot_view_test
FROM sandbox.seo_locations
WHERE location_type = 'city'
AND (nameFull like '%United States' OR nameFull like '%Canada');

-- hacky: for now, assume about 4200 cities and break 
-- into roughly equal buckets. This may change in future
-- and a better approach would be max(population_rank)/7
-- size buckets
UPDATE sandbox.as_seo_cities SET population_bucket =
CASE WHEN population_rank BETWEEN 1 AND 600 THEN 1
WHEN population_rank BETWEEN 601 AND 1200 THEN 2
WHEN population_rank BETWEEN 1201 AND 1800 THEN 3
WHEN population_rank BETWEEN 1801 AND 2400 THEN 4
WHEN population_rank BETWEEN 2401 AND 3000 THEN 5
WHEN population_rank BETWEEN 3001 AND 3600 THEN 6
ELSE 7 END ;

UPDATE sandbox.as_seo_cities SET is_in_bot_view_test = 1 
WHERE location_url IN ( 'arvada',
    'aurora-co',
    'centennial',
    'denver',
    'lakewood',
    'thornton',
    'westminster',
    'berkley-co',
    'brighton-co',
    'castle-rock-co',
    'columbine-co',
    'commerce-city-co',
    'englewood-co',
    'federal-heights-co',
    'golden-co',
    'greenwood-village-co',
    'highlands-ranch-co',
    'ken-caryl-co',
    'littleton-co',
    'northglenn-co',
    'parker-co',
    'sherrelwood-co',
    'welby-co',
    'wheat-ridge-co')
;

-- Now, get every city name on its own, and its nameMedShort version
-- (only when nameMedShort is not the same as name) 
-- and then append "deals" to those as well
INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000), 
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT name AS keyword,
		'/local/' || location_url AS local_url,
		-1 as category_seo_id,
		location_id,
		'<city>' as query_pattern
	FROM sandbox.as_seo_cities 
) c  
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;  	

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000), 
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT nameMedShort AS keyword,
		'/local/' || location_url AS local_url,
		-1 AS category_seo_id,
		location_id,
		'<cityMedShort>' AS query_pattern
	FROM sandbox.as_seo_cities
	WHERE name <> nameMedShort
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;


INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT name || ' deals' AS keyword,
		'/local/' || location_url AS local_url,
		-1 AS category_seo_id,
		location_id,
		'<city> deals' AS query_pattern
	FROM sandbox.as_seo_cities
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;		

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT nameMedShort || ' deals' AS keyword,
		'/local/' || location_url AS local_url,
		-1 AS category_seo_id,
		location_id,
		'<cityMedShort> deals' AS query_pattern
	FROM sandbox.as_seo_cities
	WHERE name <> nameMedShort
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;		

-- then get each category on its own, locationless 
INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT singular AS keyword, 
	  '/local/' || url AS local_url,
	  seo_id AS category_seo_id,
	  null AS location_id,
	  '<category singular>' AS query_pattern
	FROM sandbox.seo_categories_with_names 
	WHERE name <> 'ALL'
	AND singular IS NOT NULL 
	GROUP BY 1,2,3,4,5 
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT plural AS keyword, 
	  '/local/' || url AS local_url,
	  seo_id AS category_seo_id,
	  null AS location_id,
	  '<category plural>' AS query_pattern
	FROM sandbox.seo_categories_with_names
	WHERE plural <> 'ALL' 
	AND singular IS NOT NULL 
	AND plural <> singular
	GROUP BY 1,2,3,4,5  
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

-- then for each category and city, get the combinations of 
-- [Category Singular] + [City]
-- [Category Singular] + in + [City]
-- [City] + [Category Singular] 
-- [Category Plural] + [City]
-- [Category Plural] + in + [City]
-- [City] + [Category Plural]
-- doing those plural ones only where category plural differs from cateogry singular
-- and then do the same for [CityMedShort]

-- for city
INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.singular || ' ' || ci.name AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<category singular> <city>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca
	WHERE ca.name <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.singular || ' in ' || ci.name AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
	    '<category singular> in <city>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca
	WHERE ca.name <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ci.name || ' ' || ca.singular AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<city> <category singular>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca
	WHERE ca.name <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.plural || ' ' || ci.name AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<category plural> <city>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca 
	WHERE ca.plural <> ca.singular 
	AND ca.plural <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.plural || ' in ' || ci.name AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<category plural> in <city>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca 
	WHERE ca.plural <> ca.singular 
	AND ca.plural <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ci.name || ' ' || ca.plural AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<city> <category plural>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca 
	WHERE ca.plural <> ca.singular 
	AND ca.plural <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

-- for cityMedShort
INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.singular || ' ' || ci.nameMedShort AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<category singular> <cityMedShort>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca
	WHERE ci.name <> ci.nameMedShort
	AND ca.name <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.singular || ' in ' || ci.nameMedShort AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<category singular> in <city>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca
	WHERE ci.name <> ci.nameMedShort
	AND ca.name <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ci.nameMedShort || ' ' || ca.singular AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<cityMedShort> <category singular>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca
	WHERE ci.name <> ci.nameMedShort
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.plural || ' ' || ci.nameMedShort AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<category plural> <cityMedShort>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca 
	WHERE ca.plural <> ca.singular 
	AND ci.name <> ci.nameMedShort
	AND ca.plural <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ca.plural || ' in ' || ci.nameMedShort AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<category plural> in <cityMedShort>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca 
	WHERE ca.plural <> ca.singular 
	AND ci.name <> ci.nameMedShort
	AND ca.plural <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

INSERT INTO sandbox.seo_keywords_and_landings
SELECT RANDOM(1,100000),
	c.keyword,
	c.local_url,
	c.category_seo_id,
	c.location_id,
	c.query_pattern
FROM 
(
	SELECT ci.nameMedShort || ' ' || ca.plural AS keyword,
		'/local/' || ci.location_url || '/' || ca.url AS local_url,
		ca.seo_id AS category_seo_id,
		ci.location_id,
		'<cityMedShort> <category plural>' AS query_pattern
	FROM sandbox.as_seo_cities ci, sandbox.seo_categories_with_names ca 
	WHERE ca.plural <> ca.singular 
	AND ci.name <> ci.nameMedShort
	AND ca.plural <> 'ALL'
	AND ca.singular IS NOT NULL
) c 
LEFT JOIN sandbox.seo_keywords_and_landings kl 
ON c.keyword = kl.keyword AND c.local_url = kl.local_url 
WHERE kl.keyword IS NULL ;

.QUIT 
EOF
